# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
description = "ClipClap Moderation Gateway — Fastly Compute adapter"
language = "rust"
manifest_version = 3
name = "wasm-prompt-firewall"
service_id = "P6OGBpYSN19w9UxuaAfbdi"

[local_server]

  [local_server.backends]

    [local_server.backends.inference]
      url = "http://127.0.0.1:8000"

  [local_server.config_stores]

    [local_server.config_stores.gateway_config]
      format = ""

      [local_server.config_stores.gateway_config.contents]
        gateway_platform = "Fastly Compute"
        gateway_region = "global (edge)"
        inference_url = "http://127.0.0.1:8000"

  [local_server.kv_stores]

    [local_server.kv_stores.moderation_cache]
      file = "kv_store.json"
      format = "json"
